name: Create main pull request
on:
  push:
    branches:
      - main
jobs:
  updateAuthor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - name: Reset master branch
        run: |
          git fetch origin test:test
          git reset --hard test
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: master-promotion
